# Generated by Django 3.2.5 on 2022-07-28 08:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0002_alter_reviewmodel_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewmodel',
            name='stars',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
