# Generated by Django 3.2.5 on 2022-07-26 10:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='heart_rate',
            field=models.IntegerField(default=60, validators=[django.core.validators.MinLengthValidator(60), django.core.validators.MaxLengthValidator(150)]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.IntegerField(validators=[django.core.validators.MinLengthValidator(18), django.core.validators.MaxLengthValidator(35)]),
        ),
    ]
